/**************************************************************************
 Program:  Format_indac05f.sas
 Library:  Ipums
 Project:  NeighborhoodInfo DC
 Author:   P. Tatian
 Created:  08/24/07
 Version:  SAS 9.1
 Environment:  Windows
 
 Description:  Codes for Industry (IND) and NAICS Industry (INDNAICS) 
 in the 2000 Census and ACS Samples.

 Modifications:
**************************************************************************/

%include "K:\Metro\PTatian\DCData\SAS\Inc\Stdhead.sas";

** Define libraries **;
%DCData_lib( Ipums )

proc format library=Ipums;

  value indac05f
    0 = "Not applicable"
    17 = "Crop production"
    18 = "Animal production"
    19 = "Forestry except logging"
    27 = "Logging"
    28 = "Fishing, hunting, and trapping"
    29 = "Support activities for agriculture and forestry"
    37 = "Oil and gas extraction"
    38 = "Coal mining"
    39 = "Metal ore mining"
    47 = "Nonmetallic mineral mining and quarrying"
    48 = "Not specified type of mining"
    49 = "Support activities for mining"
    57 = "Electric power generation, transmission and distribution"
    58 = "Natural gas distribution"
    59 = "Electric and gas, and other combinations"
    67 = "Water, steam, air conditioning, and irrigation systems"
    68 = "Sewage treatment facilities"
    69 = "Not specified utilities"
    77 = "Construction"
    107 = "Animal food, grain and oilseed milling"
    108 = "Sugar and confectionery products"
    109 = "Fruit and vegetable preserving and specialty foods"
    117 = "Dairy products"
    118 = "Animal slaughtering and processing"
    119 = "Retail bakeries"
    127 = "Bakeries, except retail"
    128 = "Seafood and other miscellaneous foods, n.e.c."
    129 = "Not specified food industries"
    137 = "Beverage"
    139 = "Tobacco"
    147 = "Fiber, yarn, and thread mills"
    148 = "Fabric mills, except knitting"
    149 = "Textile and fabric finishing and coating mills"
    157 = "Carpets and rugs"
    159 = "Textile product mills except carpets and rugs"
    167 = "Knitting mills"
    168 = "Cut and sew apparel"
    169 = "Apparel accessories and other apparel"
    177 = "Footwear"
    179 = "Leather tanning and products, except footwear"
    187 = "Pulp, paper, and paperboard mills"
    188 = "Paperboard containers and boxes"
    189 = "Miscellaneous paper and pulp products"
    199 = "Printing and related support activities"
    207 = "Petroleum refining"
    209 = "Miscellaneous petroleum and coal products"
    217 = "Resin, synthetic rubber and fibers, and filaments"
    218 = "Agricultural chemicals"
    219 = "Pharmaceuticals and medicines"
    227 = "Paint, coating, and adhesives"
    228 = "Soap, cleaning compound, and cosmetics"
    229 = "Industrial and miscellaneous chemicals"
    237 = "Plastics products"
    238 = "Tires"
    239 = "Rubber products, except tires"
    247 = "Pottery, ceramics, and related products"
    248 = "Structural clay products"
    249 = "Glass and glass products"
    257 = "Cement, concrete, lime, and gypsum products"
    259 = "Miscellaneous nonmetallic mineral products"
    267 = "Iron and steel mills and steel products"
    268 = "Aluminum production and processing"
    269 = "Nonferrous metal, except aluminum, production and processing"
    277 = "Foundries"
    278 = "Metal forgings and stampings"
    279 = "Cutlery and hand tools"
    287 = "Structural metals, and tank and shipping containers"
    288 = "Machine shops; turned products; screws, nuts and bolts"
    289 = "Coating, engraving, heat treating and allied activities"
    297 = "Ordnance"
    298 = "Miscellaneous fabricated metal products"
    299 = "Not specified metal industries"
    307 = "Agricultural implements"
    308 = "Construction mining and oil field machinery"
    309 = "Commercial and service industry machinery"
    317 = "Metalworking machinery"
    318 = "Engines, turbines, and power transmission equipment"
    319 = "Machinery, n.e.c."
    329 = "Not specified machinery"
    336 = "Computer and peripheral equipment"
    337 = "Communications, audio, and video equipment"
    338 = "Navigational, measuring, electromedical, and control instruments"
    339 = "Electronic components and products, n.e.c."
    347 = "Household appliances"
    349 = "Electrical machinery, equipment, and supplies, n.e.c."
    357 = "Motor vehicles and motor vehicle equipment"
    358 = "Aircraft and parts"
    359 = "Aerospace products and parts"
    367 = "Railroad rolling stock"
    368 = "Ship and boat building"
    369 = "Other transportation equipment"
    377 = "Sawmills and wood preservation"
    378 = "Veneer, plywood, and engineered wood products"
    379 = "Prefabricated wood buildings and mobile homes"
    387 = "Miscellaneous wood products"
    389 = "Furniture and fixtures"
    396 = "Medical equipment and supplies"
    397 = "Toys, amusement, and sporting goods"
    398 = "Miscellaneous manufacturing, n.e.c."
    399 = "Not specified industries"
    407 = "Motor vehicles, parts and supplies"
    408 = "Furniture and home furnishing"
    409 = "Lumber and other construction materials"
    417 = "Professional and commercial equipment and supplies"
    418 = "Metals and minerals, except petroleum"
    419 = "Electrical goods"
    426 = "Hardware, plumbing and heating equipment, and supplies"
    427 = "Machinery, equipment, and supplies"
    428 = "Recyclable material"
    429 = "Miscellaneous durable goods"
    437 = "Paper and paper products"
    438 = "Drugs, sundries, and chemical and allied products"
    439 = "Apparel, fabrics, and notions"
    447 = "Groceries and related products"
    448 = "Farm product raw materials"
    449 = "Petroleum and petroleum products"
    456 = "Alcoholic beverages"
    457 = "Farm supplies"
    458 = "Electronic markets, agents and brokers, miscellaneous nondurable goods"
    459 = "Not specified trade"
    467 = "Automobile dealers"
    468 = "Other motor vehicle dealers"
    469 = "Auto parts, accessories, and tire stores"
    477 = "Furniture and home furnishings stores"
    478 = "Household appliance stores"
    479 = "Radio, tv, and computer stores"
    487 = "Building material and supplies dealers"
    488 = "Hardware stores"
    489 = "Lawn and garden equipment and supplies stores"
    497 = "Grocery stores"
    498 = "Specialty food stores"
    499 = "Beer, wine, and liquor stores"
    507 = "Pharmacies and drug stores"
    508 = "Health and personal care, except drug, stores"
    509 = "Gasoline stations"
    517 = "Clothing and accessories, except shoe, stores"
    518 = "Shoe stores"
    519 = "Jewelry, luggage,and leather goods stores"
    527 = "Sporting goods, camera, and hobby and toy stores"
    528 = "Sewing, needlework and piece goods stores"
    529 = "Music stores"
    537 = "Book stores and news dealers"
    538 = "Department stores"
    539 = "Miscellaneous general merchandise stores"
    547 = "Florists"
    548 = "Office supplies and stationary stores"
    549 = "Used merchandise stores"
    557 = "Gift, novelty, and souvenir shops"
    558 = "Miscellaneous stores"
    559 = "Electronic shopping and mail-order houses"
    567 = "Vending machine operators"
    568 = "Fuel dealers"
    569 = "Other direct selling establishments"
    579 = "Not specified trade"
    607 = "Air transportation"
    608 = "Rail transportation"
    609 = "Water transportation"
    617 = "Truck transportation"
    618 = "Bus service and urban transit"
    619 = "Taxi and limousine service"
    627 = "Pipeline transportation"
    628 = "Scenic and sightseeing transportation"
    629 = "Services incidental to transportation"
    637 = "Postal service"
    638 = "Couriers and messengers"
    639 = "Warehousing and storage"
    647 = "Newspaper publishers"
    648 = "Publishing, except newspapers and software"
    649 = "Software publishing"
    657 = "Motion pictures and video industries"
    659 = "Sound recording industries"
    667 = "Radio and television broadcasting and cable, internet publishing"
    668 = "Wired telecommunications carriers"
    669 = "Other telecommunication services, internet service providers"
    677 = "Libraries and archives"
    678 = "Other information services"
    679 = "Data processing services"
    687 = "Banking and related activities"
    688 = "Savings institutions, including credit unions"
    689 = "Non-depository credit and related activities"
    697 = "Securities, commodities, funds, trusts, and other financial investments"
    699 = "Insurance carriers and related activities"
    707 = "Real estate"
    708 = "Automotive equipment rental and leasing"
    717 = "Video tape and disk rental"
    718 = "Other consumer goods rental"
    719 = "Commercial, industrial, and other intangible assets rental and leasing"
    727 = "Legal services"
    728 = "Accounting, tax preparation, bookkeeping and payroll services"
    729 = "Architectural, engineering, and related services"
    737 = "Specialized design services"
    738 = "Computer systems design and related services"
    739 = "Management, scientific and technical consulting services"
    746 = "Scientific research and development services"
    747 = "Advertising and related services"
    748 = "Veterinary services"
    749 = "Other professional, scientific and technical services"
    757 = "Management of companies and enterprises"
    758 = "Employment services"
    759 = "Business support services"
    767 = "Travel arrangements and reservation services"
    768 = "Investigation and security services"
    769 = "Services to buildings and dwellings"
    777 = "Landscaping services"
    778 = "Other administrative, and other support services"
    779 = "Waste management and remediation services"
    786 = "Elementary and secondary schools"
    787 = "Colleges, including junior colleges, and universities"
    788 = "Business, technical, and trade schools and training"
    789 = "Other schools, instruction and educational services"
    797 = "Offices of physicians"
    798 = "Offices of dentists"
    799 = "Office of chiropractors"
    807 = "Offices of optometrists"
    808 = "Offices of other health practitioners"
    809 = "Outpatient care centers"
    817 = "Home health care services"
    818 = "Other health care services"
    819 = "Hospitals"
    827 = "Nursing care facilities"
    829 = "Residential care facilities, without nursing"
    837 = "Individual and family services"
    838 = "Community food and housing, and emergency services"
    839 = "Vocational rehabilitation services"
    847 = "Child day care services"
    856 = "Independent artists, performing arts, spectator sports and related industries"
    857 = "Museums, art galleries, historical sites, and similar institutions"
    858 = "Bowling centers"
    859 = "Other amusement, gambling, and recreation industries"
    866 = "Traveler accommodation"
    867 = "Recreational vehicle parks and camps, and rooming and boarding houses"
    868 = "Restaurants and other food services"
    869 = "Drinking places, alcohol beverages"
    877 = "Automotive repair and maintenance"
    878 = "Car washes"
    879 = "Electronic and precision equipment repair and maintenance"
    887 = "Commercial and industrial machinery and equipment repair and maintenance"
    888 = "Personal and household goods repair and maintenance"
    889 = "Footwear and leather goods repair"
    897 = "Barber shops"
    898 = "Beauty salons"
    899 = "Nail salons and other personal care services"
    907 = "Drycleaning and laundry services"
    908 = "Funeral homes, cemeteries and crematories"
    909 = "Other personal services"
    916 = "Religious organizations"
    917 = "Civic, social, advocacy organizations and grantmaking and giving services"
    918 = "Labor unions"
    919 = "Business, professional, political and similar organizations"
    929 = "Private households"
    937 = "Executive offices and legislative bodies"
    938 = "Public finance activities"
    939 = "Other general government and support"
    947 = "Justice, public order, and safety activities"
    948 = "Administration of human resource programs"
    949 = "Administration of environmental quality and housing programs"
    957 = "Administration of economic programs and space research"
    959 = "National security and international affairs"
    967 = "U.S. Army"
    968 = "U.S. Air Force"
    969 = "U.S. Navy"
    977 = "U.S. Marines"
    978 = "U.S. Coast Guard"
    979 = "U.S. Armed forces, branch not specified"
    987 = "Military reserves or national guard"
    992 = "Unemployed, with no work experience in past 5 years";

run;

proc catalog catalog=Ipums.formats;
  modify indac05f (desc="Industry codes for Census 2000 & ACS") / entrytype=format;

quit;

run;
